name: nuevoyapita
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  get: ^4.7.2
  flutter_svg: ^2.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  firebase_database: ^12.0.4
  cloud_firestore: ^6.1.0
  permission_handler: ^12.0.1
  camera: ^0.11.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/


